// import a_guy from '../public/img/a_guy.png';

export const drawings = [
  {
    title: "a_guy",
    img: "/img/a_guy.png",
    guestArtist: false,
    size: 3,
  },
  {
    title: "celly",
    img: "/img/celly.png",
    guestArtist: false,
    size: 3,
  },
  {
    title: "cheeseman",
    img: "/img/cheeseman.png",
    guestArtist: false,
    size: 3,
  },
  {
    title: "nud",
    img: "/img/nud.png",
    guestArtist: false,
    size: 3,
  },
  {
    title: "porp",
    img: "/img/porp.png",
    guestArtist: false,
    size: 3,
  },
  {
    title: "haunted_sperm",
    img: "/img/haunted_sperm.png",
    guestArtist: false,
    size: 3,
  },
  {
    title: "look_in_the_mirror",
    img: "/img/look_in_the_mirror.png",
    guestArtist: false,
    size: 3,
  },
  {
    title: "4squares-4-1-21.png",
    img: "/img/4squares-4-1-21.png",
    guestArtist: false,
    size: 3,
  },
  {
    title: "4squares-4-1-21-2.png",
    img: "/img/4squares-4-1-21-2.png",
    guestArtist: false,
    size: 2,
  },
  {
    title: "4squares-4-1-21-3.png",
    img: "/img/4squares-4-1-21-3.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "4squares-4-1-21-4.png",
    img: "/img/4squares-4-1-21-4.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "4squares4-5-21",
    img: "/img/4squares4-5-21.png",
    guestArtist: false,
    size: 3,
  },
  {
    title: "4squares4-5-21-2",
    img: "/img/4squares4-5-21-2.png",
    guestArtist: false,
    size: 2,
  },
  {
    title: "4squares4-5-21-3",
    img: "/img/4squares4-5-21-3.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "4squares4-5-21-4",
    img: "/img/4squares4-5-21-4.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "dotted_samurai",
    img: "/img/dotted_samurai.png",
    guestArtist: false,
    size: 3,
  },
  {
    title: "E",
    img: "/img/E.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "grumpy_pig",
    img: "/img/grumpy_pig.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "L",
    img: "/img/L.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "me_going_ahhhhhh",
    img: "/img/me_going_ahhhhhh.png",
    guestArtist: false,
    size: 2,
  },
  {
    title: "O",
    img: "/img/O.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "oh_shiiiiii",
    img: "/img/oh_shiiiiii.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "rock_on",
    img: "/img/rock_on.png",
    guestArtist: false,
    size: 3,
  },
  {
    title: "scale_pyramid",
    img: "/img/scale_pyramid.png",
    guestArtist: false,
    size: 2,
  },
  {
    title: "soon",
    img: "/img/soon.png",
    guestArtist: false,
    size: 2,
  },
  {
    title: "stick_monkey",
    img: "/img/stick_monkey.png",
    guestArtist: false,
    size: 2,
  },
  {
    title: "V",
    img: "/img/V.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "whaaa",
    img: "/img/whaaa.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "you_have_seen_nothing",
    img: "/img/you_have_seen_nothing.png",
    guestArtist: false,
    size: 3,
  },
  {
    title: "corn_muffin_thoughts",
    img: "/img/corn_muffin_thoughts.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "happy_coffee",
    img: "/img/happy_coffee.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "hash_checks",
    img: "/img/hash_checks.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "house",
    img: "/img/house.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "i_see_you",
    img: "/img/i_see_you.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "knightball_player",
    img: "/img/knightball_player.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "odd_thumb",
    img: "/img/odd_thumb.png",
    guestArtist: false,
    size: 2,
  },
  {
    title: "pop",
    img: "/img/pop.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "swirl_pattern",
    img: "/img/swirl_pattern.png",
    guestArtist: false,
    size: 1,
  },
  {
    title: "tree_and_shrub",
    img: "/img/tree_and_shrub.png",
    guestArtist: false,
    size: 2,
  },
];